-- 코드를 입력하세요
# SELECT B.TITLE, B.BOARD_ID, A.REPLY_ID, A.WRITER_ID, A.CONTENTS, DATE_FORMAT(A.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_REPLY AS A 
# INNER JOIN USED_GOODS_BOARD AS B ON A.BOARD_ID = B.BOARD_ID
# WHERE SUBSTR(A.CREATED_DATE,1,7)='2022-10'
# ORDER BY A.CREATED_DATE ASC, B.TITLE ASC ;

SELECT  A.TITLE
        , A.BOARD_ID
        , B.REPLY_ID
        , B.WRITER_ID
        , B.CONTENTS
        , DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CRAETED_DATE
  FROM  USED_GOODS_BOARD AS A
 INNER
  JOIN  USED_GOODS_REPLY AS B
    ON  A.BOARD_ID = B.BOARD_ID
 WHERE  SUBSTR(A.CREATED_DATE,1,7) = '2022-10'
 ORDER
    BY  B.CREATED_DATE ASC, A.TITLE ASC;